name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # This step installs the nightly toolchain and sets it as default
      - name: Install Nightly Toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build
        run: cargo build --verbose

      - name: Make test dir
        run: mkdir ./test/

      - name: Run tests
        run: cargo test --verbose
